name: CI-Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Xvfb
        run: sudo apt-get install xvfb

      - name: Set up Xvfb
        run: |
          echo 'Xvfb :99 -screen 0 1280x1024x24' | sudo tee /etc/init/xvfb.conf
          sudo service xvfb start

      - name: Set up display
        run: export DISPLAY=:99

      - name: Run Tests
        run: pytest tests/
